cpu-bind=MASK - bp1-compute067, task  0  0 [1996570]: mask 0x400000400000 set
Traceback (most recent call last):
  File "/user/home/zj22662/photon-net/calc_test_loss.py", line 47, in <module>
    iterate_models(output_folder, results_subfolder, input_config)
  File "/user/home/zj22662/photon-net/calc_test_loss.py", line 37, in iterate_models
    utils.evaluate_and_save_test_loss(
  File "/user/home/zj22662/photon-net/p_pack/utils.py", line 146, in evaluate_and_save_test_loss
    loss_val, _ = loss.loss(
                  ^^^^^^^^^^
TypeError: loss() missing 1 required positional argument: 'shuffle_type'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
